branches:
  only:
  - "/^\\d+\\.\\d+/"

dist: jammy

language: node_js

node_js:
  - stable

sudo: false

before_install:
  - npm install -g pnpm
  - pnpm --version

install:
  - pnpm install

script:
  - components/bin/version
  - pnpm -s link:full
  - pnpm -s build-all

before_deplay:
  - npm install -g npm@9
  - npm config fix

deploy:
  provider: npm
  email: manager@mathjax.org
  api_key:
    secure: tKo38UbinY2eEkrzOqzYskaSQ4MDo9sD6j2i+t+cL6H03uwfPI0l1cx9YXIBDLK0CeJNFvy+aT6KB2IBtwv3/VfxSY14/IlmB2hXSXnwAFmnsv3Okejh73USceb+1kH4UTKIpP1B49tL+qtJPs/y5j4cpCZPGvYAf2BqI/EQyd1ENsj7wnz0+MQ9Bu+86aA9x7uUsDVPKVpl6yr3nx+nlQbwt8NVccGNLCZIzs6Fo+au8uqh3/IEYhstXFU/SxN3vNdJHKHUCWYAQDn2sJPjBVd1jEAmQkdLAr0DfOA73JnYF6R6C3peLy4MkXOSQWv4lo50ODNi+DRns4S97UvnJw9nWOrgey2mVcIkziiMyXQnogQ0Zu6IyMsRohI/wbaqNKkXZnNTmmTxzLZjZAeBl8EEfEStS3stnh8rMsJENuBKN7eNC3Ps0xJKOBaEIZjgVKA8GH6Vot1yzCMG9Ad4vne+EurEkPw/Bk6WAZ0wXBu56vlv1OGSUOOmYWZx7aA1xKtOahSrL+Y1mIyByBAFmZL22y8BUZF8QImaielnnv5rKXjl5ilEpcnSDZX0b6VC2FqEN5EmGwXAN1PyffC++K4Q0eS3VDD0p1ZQxGRL4dpsZE/ue9AKujdNGeNXJkFTaOKXDSD47nFw+dNt0dPvWwHJb9l7sW811Xe2N9YH4bo=
  on:
    tags: true
  skip_cleanup: true

